In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout
from tensorflow.keras.utils import plot_model

C:\Users\s\AppData\Local\Temp\ipykernel_13848\2709194421.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [674]:
fall_data = []
adl_data = []
fall_path = "up"
adl_path = "down"

In [675]:
for file in os.listdir(fall_path):
    if file.endswith(".csv"):
        data = pd.read_csv(os.path.join(fall_path, file)).values
        fall_data.append(data)

for file in os.listdir(adl_path):
    if file.endswith(".csv"):
        data = pd.read_csv(os.path.join(adl_path, file)).values
        adl_data.append(data)

In [676]:
fall_data_np = np.array(fall_data)
adl_data_np = np.array(adl_data)
fall_data_np.shape, adl_data_np.shape

((50, 75, 1), (50, 75, 1))

In [677]:
fall_data_np_re = fall_data_np.reshape(-1, 75, 1)
adl_data_np_re = adl_data_np.reshape(-1, 75, 1)

In [678]:
fall_labels = np.ones(fall_data_np_re.shape[0])
adl_labels = np.zeros(adl_data_np_re.shape[0])

In [679]:
fall_labels,adl_labels

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [680]:
fall_labels.shape, type(fall_labels)

((50,), numpy.ndarray)

In [681]:
x = np.concatenate([fall_data_np_re, adl_data_np_re], axis=0)
x.shape, type(x)

((100, 75, 1), numpy.ndarray)

In [682]:
y = np.concatenate([fall_labels, adl_labels], axis=0)
y.shape, type(y)

((100,), numpy.ndarray)

In [683]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
type(x_train), x_train.shape

(numpy.ndarray, (80, 75, 1))

In [684]:
x_train_re = x_train.reshape(x_train.shape[0], 75, 1, 1) 
x_test_re = x_test.reshape(x_test.shape[0], 75, 1, 1)

In [685]:
x_train_re.shape, x_test_re.shape

((80, 75, 1, 1), (20, 75, 1, 1))

In [686]:
x_train_re[0]

array([[[ 558]],

       [[1303]],

       [[ 962]],

       [[ 816]],

       [[ 856]],

       [[1008]],

       [[1216]],

       [[ 925]],

       [[1682]],

       [[1173]],

       [[1070]],

       [[1459]],

       [[1464]],

       [[ 980]],

       [[1726]],

       [[1556]],

       [[ 946]],

       [[1588]],

       [[1674]],

       [[1715]],

       [[1808]],

       [[2075]],

       [[2061]],

       [[2334]],

       [[1741]],

       [[4095]],

       [[2483]],

       [[3201]],

       [[3161]],

       [[2513]],

       [[2373]],

       [[2581]],

       [[2872]],

       [[2768]],

       [[3078]],

       [[2690]],

       [[2261]],

       [[2235]],

       [[2013]],

       [[2045]],

       [[1479]],

       [[1456]],

       [[1438]],

       [[ 802]],

       [[ 443]],

       [[ 213]],

       [[  65]],

       [[ 241]],

       [[ 653]],

       [[ 848]],

       [[1195]],

       [[1177]],

       [[1401]],

       [[1287]],

       [[1623]],

       [[1

In [687]:
x_train_re[0].shape

(75, 1, 1)

In [688]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(16, (1, 1), activation='relu', input_shape=x_train_re[0].shape))
model.add(Dropout(0.1))
model.add(Conv2D(32, (1, 1), activation='relu'))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_36 (Conv2D)          (None, 75, 1, 16)         32        
                                                                 
 dropout_54 (Dropout)        (None, 75, 1, 16)         0         
                                                                 
 conv2d_37 (Conv2D)          (None, 75, 1, 32)         544       
                                                                 
 dropout_55 (Dropout)        (None, 75, 1, 32)         0         
                                                                 
 flatten_18 (Flatten)        (None, 2400)              0         
                                                                 
 dense_36 (Dense)            (None, 64)                153664    
                                                                 
 dropout_56 (Dropout)        (None, 64)              

In [689]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [690]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=1)


Epoch 1/10
2/2 [==============================] - 1s 294ms/step - loss: 130.5179 - accuracy: 0.5625 - val_loss: 27.9512 - val_accuracy: 0.6250
Epoch 2/10
2/2 [==============================] - 0s 57ms/step - loss: 103.7577 - accuracy: 0.5469 - val_loss: 26.4722 - val_accuracy: 0.5625
Epoch 3/10
2/2 [==============================] - 0s 54ms/step - loss: 83.6605 - accuracy: 0.4688 - val_loss: 26.2872 - val_accuracy: 0.5625
Epoch 4/10
2/2 [==============================] - 0s 57ms/step - loss: 60.2315 - accuracy: 0.5312 - val_loss: 18.6035 - val_accuracy: 0.5625
Epoch 5/10
2/2 [==============================] - 0s 57ms/step - loss: 30.0723 - accuracy: 0.6250 - val_loss: 17.0182 - val_accuracy: 0.6250
Epoch 6/10
2/2 [==============================] - 0s 59ms/step - loss: 34.1642 - accuracy: 0.6875 - val_loss: 15.1903 - val_accuracy: 0.4375
Epoch 7/10
2/2 [==============================] - 0s 56ms/step - loss: 27.0903 - accuracy: 0.6562 - val_loss: 13.5081 - val_accuracy: 0.4375
Epoch 8/10

In [789]:
df4 = pd.read_csv("up/up_20.csv")

In [790]:
df6 = df4.values

In [791]:
df6_re = df6.reshape(-1, 75, 1)

In [792]:
y_pred6 = model.predict(df6_re)

1/1 [==============================] - 0s 27ms/step


In [793]:
prediction_result = "Upward movement" if y_pred6[0][0] >= 0.5 else "Downward movement"

In [794]:
y_pred6[0][0]

9.621696e-27

In [795]:
print("Prediction:", prediction_result)

Prediction: Downward movement
